{% set version = "0.10.4" %}
{%set hash_type = "sha256" %}
{%set hash_val = "fe2dda718c8ac24e20856478613817693c913483e87bcc4b4e688eec344078dd" %}

package:
  name: ggplot
  version: {{ version }}

source:
  fn: ggplot-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/ggplot/ggplot-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - brewer2mpl
    - cycler
    - matplotlib
    - numpy
    - pandas
    - patsy >=0.4
    - scipy
    - six
    - statsmodels

  run:
    - python
    - brewer2mpl
    - cycler
    - matplotlib
    - numpy
    - pandas
    - patsy >=0.4
    - scipy
    - six
    - statsmodels

test:
  imports:
    - ggplot

about:
  home: https://github.com/yhat/ggplot
  license: BSD 2-Clause
  summary: 'ggplot for python'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
