{% set version = "0.11.2" %}
{%set hash_type = "sha256" %}
{%set hash_val = "b01df3498865281730d137455df53fbd7b8c313dbdcc2a7275598f1f9df8dd08" %}

package:
  name: ggplot
  version: {{ version }}

source:
  fn: ggplot-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/ggplot/ggplot-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - brewer2mpl
    - cycler
    - matplotlib
    - numpy
    - pandas
    - patsy >=0.4
    - scipy
    - six
    - statsmodels

  run:
    - python
    - brewer2mpl
    - cycler
    - matplotlib
    - numpy
    - pandas
    - patsy >=0.4
    - scipy
    - six
    - statsmodels

test:
  imports:
    - ggplot

about:
  home: https://github.com/yhat/ggplot
  license: BSD 2-Clause
  summary: 'ggplot for python'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
