travis:
  secure:
    BINSTAR_TOKEN: HQDZ5BeZ4YK4NQ7uX3Q8WfXGmD0viUGOyj6oA1odGv2kKEwv/4+/TnuZHZFY5McU12VamdLBxsrOR2sGkUwn8tg9PXvCasjSOeIgghYh9qpks40XjIB0cRm44vpHS/SILQHGFFdLomEImg5I5eLLRnkAR4p+ISA1cdTUTEFzCPxeKUzRLpVbKxaRbDwP01A2rmmWmUvFVjCam8Vb/EbYyLG2SB57ZAweeL+JzNIsc638NzNAdkRtoVf6fqTp3bvItmCklQhDiRvyIBJzEXgO1/9aCKweySu/ZLmknneoscWpc6BnOBhB4E59kGb+++mvVZo3JbIaY62bMSN/bt5by50JWoDd3H0WvvDG0zRIUltJ7X89GBBtTbVEJCr4BfFuAl+rI2gsEaeA6NMQSpxibqB2SRW3QAL9cBfZ00wzF7r+lR93MUBZnsfO7B2RaT3GGKLg0wKB4IDKY3CfxLK2ru+xGe566ngVvT3aAcPjM5nUPFcHehngQBoC0udSnxC0usT0P5vqWNnvKqF3Y1YHV5n/kBlUYuG93FwizcE7e/dZfzGehGebIe0TknRuql5CJDrnKPMcLF9vR12NMoBb/V8LX8etfbcuommkx/4yeQ5L40WJi8hqt6HRp9/60GJCobA1tZ7sYbcUGNGz6SWem/5m2BMDmoLicLOoog7jqrk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
